### ISSUE TITLE
App can't be loaded

### ISSUE THREAD

**Issue by frankhuurman** [streamlit/roadmap#5]
I'm trying to view the roadmap(by visiting: https://share.streamlit.io/streamlit/roadmap/) but apparently the app can't be loaded properly for the past few hours:
![image](https://user-images.githubusercontent.com/19980966/150809705-47685ccc-23fa-4302-8823-0c5035ebaa3b.png)

**Comment by randyzwitch** [comment]
This has been fixed, thanks for letting us know @frankhuurman!
